import logo from "./imgs/logo192.png";
export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
  },
  {
    name: "Feb",
    "Active User": 3000,
  },
  {
    name: "Mar",
    "Active User": 5000,
  },
  {
    name: "Apr",
    "Active User": 4000,
  },
  {
    name: "May",
    "Active User": 3000,
  },
  {
    name: "Jun",
    "Active User": 2000,
  },
  {
    name: "Jul",
    "Active User": 4000,
  },
  {
    name: "Agu",
    "Active User": 3000,
  },
  {
    name: "Sep",
    "Active User": 4000,
  },
  {
    name: "Oct",
    "Active User": 1000,
  },
  {
    name: "Nov",
    "Active User": 4000,
  },
  {
    name: "Dec",
    "Active User": 3000,
  },
];

export const productData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 3000,
  },
  {
    name: "Mar",
    Sales: 5000,
  },
];

export const userRows = [
  {
    id: 1,
    username: "ReactJS",
    fullname: "React Js",
    avatar: logo,
    email: "react@gmail.com",
    status: "active",
    transaction: "$120.00",
    birthdate: "10.12.1999",
    occupation: "Software Engineer",
    phone: "+1 123 456 67",
    address: "New York | USA",
    gender: "other",
  },
  {
    id: 2,
    username: "ReactJS",
    fullname: "React Js",
    avatar: logo,
    email: "react@gmail.com",
    status: "active",
    transaction: "$120.00",
    birthdate: "10.12.1999",
    occupation: "Software Engineer",
    phone: "+1 123 456 67",
    address: "New York | USA",
    gender: "other",
  },
  {
    id: 3,
    username: "ReactJS",
    fullname: "React Js",
    avatar: logo,
    email: "react@gmail.com",
    status: "active",
    transaction: "$120.00",
    birthdate: "10.12.1999",
    occupation: "Software Engineer",
    phone: "+1 123 456 67",
    address: "New York | USA",
    gender: "other",
  },
  {
    id: 4,
    username: "ReactJS",
    fullname: "React Js",
    avatar: logo,
    email: "react@gmail.com",
    status: "active",
    transaction: "$120.00",
    birthdate: "10.12.1999",
    occupation: "Software Engineer",
    phone: "+1 123 456 67",
    address: "New York | USA",
    gender: "other",
  },
  {
    id: 5,
    username: "ReactJS",
    fullname: "React Js",
    avatar: logo,
    email: "react@gmail.com",
    status: "active",
    transaction: "$120.00",
    birthdate: "10.12.1999",
    occupation: "Software Engineer",
    phone: "+1 123 456 67",
    address: "New York | USA",
    gender: "other",
  },
  {
    id: 6,
    username: "ReactJS",
    fullname: "React Js",
    avatar: logo,
    email: "react@gmail.com",
    status: "active",
    transaction: "$120.00",
    birthdate: "10.12.1999",
    occupation: "Software Engineer",
    phone: "+1 123 456 67",
    address: "New York | USA",
    gender: "other",
  },
  {
    id: 7,
    username: "ReactJS",
    fullname: "React Js",
    avatar: logo,
    email: "react@gmail.com",
    status: "active",
    transaction: "$120.00",
    birthdate: "10.12.1999",
    occupation: "Software Engineer",
    phone: "+1 123 456 67",
    address: "New York | USA",
    gender: "other",
  },
  {
    id: 8,
    username: "ReactJS",
    fullname: "React Js",
    avatar: logo,
    email: "react@gmail.com",
    status: "active",
    transaction: "$120.00",
    birthdate: "10.12.1999",
    occupation: "Software Engineer",
    phone: "+1 123 456 67",
    address: "New York | USA",
    gender: "other",
  },
  {
    id: 9,
    username: "ReactJS",
    fullname: "React Js",
    avatar: logo,
    email: "react@gmail.com",
    status: "active",
    transaction: "$120.00",
    birthdate: "10.12.1999",
    occupation: "Software Engineer",
    phone: "+1 123 456 67",
    address: "New York | USA",
    gender: "other",
  },
  {
    id: 10,
    username: "ReactJS",
    fullname: "React Js",
    avatar: logo,
    email: "react@gmail.com",
    status: "active",
    transaction: "$120.00",
    birthdate: "10.12.1999",
    occupation: "Software Engineer",
    phone: "+1 123 456 67",
    address: "New York | USA",
    gender: "other",
  },
];

export const productRows = [
  {
    id: 1,
    name: "R",
    img: logo,
    stock: 123,
    status: "active",
    price: "$120.00",
    sales: 5123,
  },
  {
    id: 2,
    name: "R",
    img: logo,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 3,
    name: "R",
    img: logo,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 4,
    name: "R",
    img: logo,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 5,
    name: "R",
    img: logo,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 6,
    name: "R",
    img: logo,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 7,
    name: "R",
    img: logo,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 8,
    name: "R",
    img: logo,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 9,
    name: "R",
    img: logo,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 10,
    name: "R",
    img: logo,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
];
